# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
from pandas import DataFrame

print("Hello World!")


Hello World!


In [2]:
import pandas as pd
import numpy as np

In [3]:
def get_list_columns_names(df: pd.DataFrame):
    columns_names = "["

    for idx, col in enumerate(df.columns):
        columns_names += "\"" + col + "\""

        if (idx + 1) < len(df.columns):
            columns_names += ","

    columns_names += "]"

    return columns_names

In [4]:
df_train_operational_readouts = pd.read_csv("data/Scania_component_X/train_operational_readouts.csv")
df_train_tte = pd.read_csv("data/Scania_component_X/train_tte.csv")
df_train_specifications = pd.read_csv("data/Scania_component_X/train_specifications.csv")

print(get_list_columns_names(df_train_operational_readouts))
print(get_list_columns_names(df_train_tte))
print(get_list_columns_names(df_train_specifications))

["vehicle_id","time_step","171_0","666_0","427_0","837_0","167_0","167_1","167_2","167_3","167_4","167_5","167_6","167_7","167_8","167_9","309_0","272_0","272_1","272_2","272_3","272_4","272_5","272_6","272_7","272_8","272_9","835_0","370_0","291_0","291_1","291_2","291_3","291_4","291_5","291_6","291_7","291_8","291_9","291_10","158_0","158_1","158_2","158_3","158_4","158_5","158_6","158_7","158_8","158_9","100_0","459_0","459_1","459_2","459_3","459_4","459_5","459_6","459_7","459_8","459_9","459_10","459_11","459_12","459_13","459_14","459_15","459_16","459_17","459_18","459_19","397_0","397_1","397_2","397_3","397_4","397_5","397_6","397_7","397_8","397_9","397_10","397_11","397_12","397_13","397_14","397_15","397_16","397_17","397_18","397_19","397_20","397_21","397_22","397_23","397_24","397_25","397_26","397_27","397_28","397_29","397_30","397_31","397_32","397_33","397_34","397_35"]
["vehicle_id","length_of_study_time_step","in_study_repair"]
["vehicle_id","Spec_0","Spec_1","Sp

In [5]:
features = np.array(df_train_operational_readouts.drop(columns=["vehicle_id", "time_step"]).columns)
features = np.array([s.split('_')[0] for s in features])
features = np.unique(features)

print(f"The number of features is : {len(features)}")

The number of features is : 14


In [6]:
from utils.utils import load_train_dataset, generate_train_survival_dataset_time_varying
import constants.scania_component_x_columns as cols

from lifelines.utils import add_covariate_to_timeline, to_long_format

survival_dataset = generate_train_survival_dataset_time_varying(print_information=True)

survival_dataset.to_csv("data/survival_dataset_time_varying.csv", index=False)

#################### Train tte after to_long_format ####################
   vehicle_id  in_study_repair  start   stop
0           0            False      0  510.0
1           2            False      0  281.8
2           3            False      0  293.4
3           4            False      0  210.0
4           5            False      0  360.4
#################### Survival dataset after add_covariate_to_timeline ####################
   start     100_0    158_0      158_1      158_2     158_3     158_4  \
0    0.0       NaN      NaN        NaN        NaN       NaN       NaN   
1   11.2  858410.0  97056.0  2690052.0  2945268.0  788437.0  687480.0   
2   11.4  860571.0  97056.0  2693100.0  2947368.0  788437.0  687480.0   
3    0.0       NaN      NaN        NaN        NaN       NaN       NaN   
4    1.4  691450.0  50784.0  1965360.0  1517533.0  449437.0  316860.0   

      158_5     158_6     158_7  ...  Spec_1  Spec_2  Spec_3  Spec_4  Spec_5  \
0       NaN       NaN       NaN  ...     NaN   

In [1]:
import torch
from models.lab import TestModel

# On définit le nombre de colonnes de caractéristiques
# (en excluant les colonnes d'ID et de temps du dataset de survie)
# Si vous voulez tester sur 10 features par exemple :
num_features = 10

# Initialisation du modèle
test_model = TestModel(num_features=num_features)
test_model.train() # BatchNorm a besoin du mode train pour calculer la moyenne/variance

# Création d'un batch de test (Taille du batch = 4, Nombre de features = num_features)
sample_input = torch.randn(4, num_features)

# Test du modèle
output = test_model(sample_input)

print("\nForme de la sortie :", output.shape)

tensor([[-1.2068,  0.9321, -0.9617,  0.5164,  1.2329, -1.0119,  0.4219,  1.3600,
          1.0602, -0.8885],
        [ 0.2638, -0.6404, -0.4869,  1.4542, -1.1308,  0.0411, -1.5596,  0.5800,
         -0.2225,  1.0083],
        [-0.3146,  0.2747, -1.8248,  1.5882,  0.7568, -1.1811, -1.1739,  0.5192,
          0.9776,  1.7306],
        [-1.7229, -1.3131,  0.3549, -0.5363,  0.3117,  1.0321, -0.7007, -0.4898,
          0.9452,  0.7190]])
tensor([[-0.5995,  1.3052, -0.2942, -0.2806,  1.0636, -0.8219,  1.5804,  1.3209,
          0.7001, -1.5987],
        [ 1.3100, -0.5293,  0.3077,  0.8194, -1.6101,  0.3605, -1.0848,  0.1334,
         -1.7266,  0.3822],
        [ 0.5590,  0.5382, -1.3885,  0.9765,  0.5250, -1.0119, -0.5661,  0.0409,
          0.5439,  1.1365],
        [-1.2696, -1.3141,  1.3750, -1.5153,  0.0215,  1.4733,  0.0705, -1.4952,
          0.4826,  0.0800]], grad_fn=<NativeBatchNormBackward0>)

Forme de la sortie : torch.Size([4, 10])


In [5]:
import torch

a = torch.randint(0, 100, (4, 4))

print(f"a : {a}")
print(f"a.view : {a.view(-1)}")

b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f"b : {b}")

print(f"b.unsqueeze(0) : {b.unsqueeze(0)}")

a : tensor([[59, 58, 99, 67],
        [54, 41, 39, 18],
        [19, 11, 18, 71],
        [80, 48, 90, 99]])
a.view : tensor([59, 58, 99, 67, 54, 41, 39, 18, 19, 11, 18, 71, 80, 48, 90, 99])
b : tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
b.unsqueeze(0) : tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])


In [3]:
import pandas as pd
import constants.c_mapss_columns as c_mapss_cols

C_MAPSS_COLUMNS = [
    c_mapss_cols.UNIT_NUMBER,
    c_mapss_cols.TIME,
    c_mapss_cols.OPERATIONAL_SETTINGS_1,
    c_mapss_cols.OPERATIONAL_SETTINGS_2,
    c_mapss_cols.OPERATIONAL_SETTINGS_3,
    c_mapss_cols.SENSOR_MEASUREMENT_1,
    c_mapss_cols.SENSOR_MEASUREMENT_2,
    c_mapss_cols.SENSOR_MEASUREMENT_3,
    c_mapss_cols.SENSOR_MEASUREMENT_4,
    c_mapss_cols.SENSOR_MEASUREMENT_5,
    c_mapss_cols.SENSOR_MEASUREMENT_6,
    c_mapss_cols.SENSOR_MEASUREMENT_7,
    c_mapss_cols.SENSOR_MEASUREMENT_8,
    c_mapss_cols.SENSOR_MEASUREMENT_9,
    c_mapss_cols.SENSOR_MEASUREMENT_10,
    c_mapss_cols.SENSOR_MEASUREMENT_11,
    c_mapss_cols.SENSOR_MEASUREMENT_12,
    c_mapss_cols.SENSOR_MEASUREMENT_13,
    c_mapss_cols.SENSOR_MEASUREMENT_14,
    c_mapss_cols.SENSOR_MEASUREMENT_15,
    c_mapss_cols.SENSOR_MEASUREMENT_16,
    c_mapss_cols.SENSOR_MEASUREMENT_17,
    c_mapss_cols.SENSOR_MEASUREMENT_18,
    c_mapss_cols.SENSOR_MEASUREMENT_19,
    c_mapss_cols.SENSOR_MEASUREMENT_20,
    c_mapss_cols.SENSOR_MEASUREMENT_21
]

df_train_fd001 = pd.read_csv("data/C_MAPSS/train_FD001.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_train_fd002 = pd.read_csv("data/C_MAPSS/train_FD002.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_train_fd003 = pd.read_csv("data/C_MAPSS/train_FD003.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_train_fd004 = pd.read_csv("data/C_MAPSS/train_FD004.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_test_fd001 = pd.read_csv("data/C_MAPSS/test_FD001.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_test_fd002 = pd.read_csv("data/C_MAPSS/test_FD002.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_test_fd003 = pd.read_csv("data/C_MAPSS/test_FD003.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')
df_test_fd004 = pd.read_csv("data/C_MAPSS/test_FD004.txt", names=C_MAPSS_COLUMNS, header=None, sep='\s')

df_train_fd001.to_csv("data/C_MAPSS/train_FD001.csv")
df_train_fd002.to_csv("data/C_MAPSS/train_FD002.csv")
df_train_fd003.to_csv("data/C_MAPSS/train_FD003.csv")
df_train_fd004.to_csv("data/C_MAPSS/train_FD004.csv")
df_test_fd001.to_csv("data/C_MAPSS/test_FD001.csv")
df_test_fd002.to_csv("data/C_MAPSS/test_FD002.csv")
df_test_fd003.to_csv("data/C_MAPSS/test_FD003.csv")
df_test_fd004.to_csv("data/C_MAPSS/test_FD004.csv")


<>:33: SyntaxWarning: invalid escape sequence '\s'
<>:34: SyntaxWarning: invalid escape sequence '\s'
<>:35: SyntaxWarning: invalid escape sequence '\s'
<>:36: SyntaxWarning: invalid escape sequence '\s'
<>:37: SyntaxWarning: invalid escape sequence '\s'
<>:38: SyntaxWarning: invalid escape sequence '\s'
<>:39: SyntaxWarning: invalid escape sequence '\s'
<>:40: SyntaxWarning: invalid escape sequence '\s'
<>:33: SyntaxWarning: invalid escape sequence '\s'
<>:34: SyntaxWarning: invalid escape sequence '\s'
<>:35: SyntaxWarning: invalid escape sequence '\s'
<>:36: SyntaxWarning: invalid escape sequence '\s'
<>:37: SyntaxWarning: invalid escape sequence '\s'
<>:38: SyntaxWarning: invalid escape sequence '\s'
<>:39: SyntaxWarning: invalid escape sequence '\s'
<>:40: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Epulapp\AppData\Local\Temp\ipykernel_15708\2645372710.py:33: SyntaxWarning: invalid escape sequence '\s'
  df_train_fd001 = pd.read_csv("data/C_MAPSS/train_FD001.txt", names=C

In [8]:
import numpy as np

array = [1, 2, 3, 4, 5]

print(f"array : {array}")
print(f"array[-1]: {array[-1]}")

array3d = np.random.randint(100, size=(2, 3, 4))

print(f"array3d : {array3d}")
print(f"array3d[:, :, -1] : {array3d[:, :, -1]}")
print(f"array3d[:, -1, -1] : {array3d[:, -1, -1]}")

array : [1, 2, 3, 4, 5]
array[-1]: 5
array3d : [[[ 1 63 88 27]
  [96 86 84 20]
  [12  9 64 87]]

 [[73 93  3 58]
  [17 27 90 80]
  [51 61 46 58]]]
array3d[:, :, -1] : [[27 20 87]
 [58 80 58]]
array3d[:, -1, -1] : [87 58]


In [2]:
array = [1, 2, 3, 4, 5]

print(array[2:])

[3, 4, 5]
